source 'http://rubygems.org'

gem 'rails', '2.3.5'
gem 'warden'
gem 'devise'
gem 'will_paginate', '2.3.16'
gem 'json', '1.5.0'
gem 'settingslogic'
gem 'rdoc',  '3.8'
gem 'fastercsv'
gem 'rest-client'
gem 'mechanize'
gem 'mysql'
gem 'mysql2'
gem 'activerecord-mysql2-adapter','0.0.3'
gem 'paginate'
